// src/pages/auth/Login.tsx
import React, { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { Mail, Lock, AlertCircle, Loader2 } from 'lucide-react';
import { authService } from '../../services/auth.service';

export const Login = () => {
  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email || !password) return;

    setLoading(true);
    setErrorMsg(null);

    try {
      const res = await authService.login({ email, password });
      
      // Load profile after login to get the exact role details if needed
      await authService.getProfile();
      
      switch (res.role) {
        case 'ADMIN':
          navigate('/admin');
          break;
        case 'GOVERNMENT_OFFICER':
          navigate('/officer');
          break;
        case 'PROVIDER':
          navigate('/provider');
          break;
        case 'BUYER':
        default:
          navigate('/buyer');
          break;
      }
    } catch (err: any) {
      setErrorMsg(err.response?.data?.message || 'Invalid email or password. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-white px-4 relative overflow-hidden">
      {/* Ambient Background Glows */}
      <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-emerald-200/40 rounded-full blur-3xl animate-pulse"></div>
      <div className="absolute bottom-1/3 right-1/4 w-80 h-80 bg-sky-200/40 rounded-full blur-3xl"></div>

      {/* Decorative Image: Bottom Left */}
      <img 
        src="https://i.ibb.co/0yYZhMN0/f013f5e9-2f96-4f07-8dae-5d60087d250e.jpg"
        alt="Land aerial view"
        className="absolute bottom-0 left-0 w-40 sm:w-[32rem] object-contain pointer-events-none z-0"
        style={{ WebkitMaskImage: 'linear-gradient(to top right, black 60%, transparent 100%)', maskImage: 'linear-gradient(to top right, black 60%, transparent 100%)' }}
      />

      {/* Decorative Image: Top Right */}
      <img 
        src="https://i.ibb.co/ccmGDYJT/5ea71be8-b3a8-4cc7-84c6-ec15a7d6b37d.jpg"
        alt="Land scenery"
        className="absolute top-0 right-0 w-40 sm:w-[32rem] object-contain pointer-events-none z-0"
        style={{ WebkitMaskImage: 'linear-gradient(to bottom left, black 60%, transparent 100%)', maskImage: 'linear-gradient(to bottom left, black 60%, transparent 100%)' }}
      />

      {/* Glass Login Card */}
      <div className="w-full max-w-md p-8 glass-card-dark rounded-2xl shadow-2xl relative z-10 animate-slide-up border border-slate-800/60">
        
        {/* Logo Header */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center gap-2 mb-3">
            <span className="text-2xl font-bold tracking-tight text-white">Land<span className="text-brand-500">Lens</span></span>
          </div>
          <p className="text-slate-400 text-sm">AI-Powered Government Land Verification Portal</p>
        </div>

        {/* Alert messages */}
        {errorMsg && (
          <div className="mb-5 p-3.5 bg-rose-500/10 border border-rose-500/20 text-rose-400 text-sm rounded-xl flex items-start gap-2.5">
            <AlertCircle className="w-5 h-5 shrink-0" />
            <span>{errorMsg}</span>
          </div>
        )}

        {/* Login Form */}
        <form onSubmit={handleSubmit} className="space-y-5">
          
          {/* Email Input */}
          <div>
            <label className="block text-slate-300 text-sm font-medium mb-1.5" htmlFor="email">Email Address</label>
            <div className="relative">
              <span className="absolute inset-y-0 left-0 pl-3.5 flex items-center text-slate-500">
                <Mail className="w-5 h-5" />
              </span>
              <input 
                id="email"
                type="email" 
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
                className="w-full bg-slate-950/60 border border-slate-800/80 rounded-xl py-3 pl-11 pr-4 text-white placeholder-slate-500 focus:outline-hidden focus:border-brand-500 focus:ring-1 focus:ring-brand-500 transition-all text-sm"
                placeholder="you@domain.com" />
            </div>
          </div>

          {/* Password Input */}
          <div>
            <label className="block text-slate-300 text-sm font-medium mb-1.5" htmlFor="password">Password</label>
            <div className="relative">
              <span className="absolute inset-y-0 left-0 pl-3.5 flex items-center text-slate-500">
                <Lock className="w-5 h-5" />
              </span>
              <input 
                id="password"
                type="password" 
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
                className="w-full bg-slate-950/60 border border-slate-800/80 rounded-xl py-3 pl-11 pr-4 text-white placeholder-slate-500 focus:outline-hidden focus:border-brand-500 focus:ring-1 focus:ring-brand-500 transition-all text-sm"
                placeholder="••••••••" />
            </div>
          </div>

          {/* Submit Button */}
          <button 
            type="submit"
            disabled={!email || !password || loading}
            className="w-full mt-2 py-3 bg-gradient-to-r from-brand-600 to-emerald-600 hover:from-brand-500 hover:to-emerald-500 text-white font-semibold rounded-xl shadow-lg transition-all transform active:scale-95 disabled:opacity-50 disabled:pointer-events-none text-sm flex items-center justify-center gap-2">
            {loading && <Loader2 className="w-4 h-4 animate-spin" />}
            {loading ? 'Signing in...' : 'Sign In'}
          </button>
        </form>

        {/* Form Footer */}
        <div className="mt-8 text-center text-xs text-slate-400">
          <span>Don't have an account? </span>
          <Link to="/auth/register" className="text-brand-400 hover:text-brand-300 font-semibold transition-colors">Create account</Link>
        </div>

      </div>
    </div>
  );
};

// src/app/features/auth/login/login.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterLink],
  template: `
    <div class="min-h-screen flex items-center justify-center bg-white px-4 relative overflow-hidden">
      <!-- Ambient Background Glows -->
      <div class="absolute top-1/4 left-1/4 w-96 h-96 bg-emerald-200/40 rounded-full blur-3xl animate-pulse"></div>
      <div class="absolute bottom-1/3 right-1/4 w-80 h-80 bg-sky-200/40 rounded-full blur-3xl"></div>

      <!-- Decorative Image: Bottom Left -->
      <img 
        src="https://i.ibb.co/0yYZhMN0/f013f5e9-2f96-4f07-8dae-5d60087d250e.jpg"
        alt="Land aerial view"
        class="absolute bottom-0 left-0 w-40 sm:w-[32rem] object-contain pointer-events-none z-0"
        style="-webkit-mask-image: linear-gradient(to top right, black 60%, transparent 100%); mask-image: linear-gradient(to top right, black 60%, transparent 100%);"
      />

      <!-- Decorative Image: Top Right -->
      <img 
        src="https://i.ibb.co/ccmGDYJT/5ea71be8-b3a8-4cc7-84c6-ec15a7d6b37d.jpg"
        alt="Land scenery"
        class="absolute top-0 right-0 w-40 sm:w-[32rem] object-contain pointer-events-none z-0"
        style="-webkit-mask-image: linear-gradient(to bottom left, black 60%, transparent 100%); mask-image: linear-gradient(to bottom left, black 60%, transparent 100%);"
      />

      <!-- Glass Login Card -->
      <div class="w-full max-w-md p-8 glass-card-dark rounded-2xl shadow-2xl relative z-10 animate-slide-up border border-slate-800/60">
        
        <!-- Logo Header -->
        <div class="text-center mb-8">
          <div class="inline-flex items-center gap-2 mb-3">
            <span class="text-2xl font-bold tracking-tight text-white">Land<span class="text-brand-500">Lens</span></span>
          </div>
          <p class="text-slate-400 text-sm">AI-Powered Government Land Verification Portal</p>
        </div>

        <!-- Alert messages -->
        <div *ngIf="errorMsg" class="mb-5 p-3.5 bg-rose-500/10 border border-rose-500/20 text-rose-400 text-sm rounded-xl flex items-start gap-2.5">
          <svg class="w-5 h-5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
          <span>{{ errorMsg }}</span>
        </div>

        <!-- Login Form -->
        <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="space-y-5">
          
          <!-- Email Input -->
          <div>
            <label class="block text-slate-300 text-sm font-medium mb-1.5" for="email">Email Address</label>
            <div class="relative">
              <span class="absolute inset-y-0 left-0 pl-3.5 flex items-center text-slate-500">
                <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 12a4 4 0 10-8 0 4 4 0 008 0zm0 0v1.5a2.5 2.5 0 005 0V12a9 9 0 10-9 9m4.5-1.206a8.959 8.959 0 01-4.5 1.206" />
                </svg>
              </span>
              <input 
                id="email"
                type="email" 
                formControlName="email"
                class="w-full bg-slate-950/60 border border-slate-800/80 rounded-xl py-3 pl-11 pr-4 text-white placeholder-slate-500 focus:outline-hidden focus:border-brand-500 focus:ring-1 focus:ring-brand-500 transition-all text-sm"
                placeholder="you@domain.com" />
            </div>
            <span *ngIf="loginForm.get('email')?.touched && loginForm.get('email')?.hasError('required')" class="text-xs text-rose-500 mt-1 block">Email is required</span>
            <span *ngIf="loginForm.get('email')?.touched && loginForm.get('email')?.hasError('email')" class="text-xs text-rose-500 mt-1 block">Invalid email format</span>
          </div>

          <!-- Password Input -->
          <div>
            <label class="block text-slate-300 text-sm font-medium mb-1.5" for="password">Password</label>
            <div class="relative">
              <span class="absolute inset-y-0 left-0 pl-3.5 flex items-center text-slate-500">
                <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                </svg>
              </span>
              <input 
                id="password"
                type="password" 
                formControlName="password"
                class="w-full bg-slate-950/60 border border-slate-800/80 rounded-xl py-3 pl-11 pr-4 text-white placeholder-slate-500 focus:outline-hidden focus:border-brand-500 focus:ring-1 focus:ring-brand-500 transition-all text-sm"
                placeholder="••••••••" />
            </div>
            <span *ngIf="loginForm.get('password')?.touched && loginForm.get('password')?.hasError('required')" class="text-xs text-rose-500 mt-1 block">Password is required</span>
          </div>

          <!-- Submit Button -->
          <button 
            type="submit"
            [disabled]="loginForm.invalid || loading"
            class="w-full mt-2 py-3 bg-gradient-to-r from-brand-600 to-emerald-600 hover:from-brand-500 hover:to-emerald-500 text-white font-semibold rounded-xl shadow-lg transition-all transform active:scale-95 disabled:opacity-50 disabled:pointer-events-none text-sm flex items-center justify-center gap-2">
            <span *ngIf="loading" class="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></span>
            {{ loading ? 'Signing in...' : 'Sign In' }}
          </button>
        </form>

        <!-- Form Footer -->
        <div class="mt-8 text-center text-xs text-slate-400">
          <span>Don't have an account? </span>
          <a routerLink="/auth/register" class="text-brand-400 hover:text-brand-300 font-semibold transition-colors">Create account</a>
        </div>

      </div>
    </div>
  `
})
export class LoginComponent implements OnInit {
  private fb = inject(FormBuilder);
  private authService = inject(AuthService);
  private router = inject(Router);

  ngOnInit(): void {
    if (this.authService.isLoggedIn) {
      const role = this.authService.userRole();
      if (role) {
        this.authService.redirectBasedOnRole(role);
      } else {
        this.router.navigate(['/buyer']);
      }
    }
  }

  loginForm: FormGroup = this.fb.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required]]
  });

  loading = false;
  errorMsg: string | null = null;

  onSubmit(): void {
    if (this.loginForm.invalid) return;

    this.loading = true;
    this.errorMsg = null;

    this.authService.login(this.loginForm.value).subscribe({
      next: () => {
        // Redirection is handled in AuthService.login() using switchMap
        this.loading = false;
      },
      error: (err) => {
        this.loading = false;
        this.errorMsg = err.error?.message || 'Invalid email or password. Please try again.';
      }
    });
  }
}
