// src/components/shared/Map.tsx
import React, { useEffect, useRef, useState, useCallback } from 'react';
import mapboxgl from 'mapbox-gl';
import { mapboxService } from '../../services/mapbox.service';
import type { Property } from '../../models/property.models';
import { MapPin, Trash2, Loader2 } from 'lucide-react';
import { parseBoundaryFromDescription } from '../../utils/boundary';

interface LocationSelectedData {
  lat: number;
  lng: number;
  address: string;
  village: string;
  district: string;
  state: string;
  pincode: string;
  area?: number;
  boundary?: [number, number][];
}

interface MapProps {
  properties?: Property[];
  mode?: 'view' | 'picker' | 'detail';
  center?: [number, number];
  zoom?: number;
  pickerLat?: number;
  pickerLng?: number;
  initialBoundary?: [number, number][];
  onLocationSelected?: (data: LocationSelectedData) => void;
}

// ─── Math Helpers ──────────────────────────────────────────────────
const calculateCentroid = (points: [number, number][]): [number, number] => {
  let sumLng = 0;
  let sumLat = 0;
  points.forEach(pt => {
    sumLng += pt[0];
    sumLat += pt[1];
  });
  return [sumLng / points.length, sumLat / points.length];
};

const calculatePolygonArea = (points: [number, number][]): number => {
  if (points.length < 3) return 0;
  const R = 6378137; // Earth radius in meters
  const xCoords = points.map(pt => pt[0] * Math.PI / 180 * R * Math.cos(pt[1] * Math.PI / 180));
  const yCoords = points.map(pt => pt[1] * Math.PI / 180 * R);

  let area = 0;
  const j = xCoords.length - 1;
  for (let i = 0; i < xCoords.length; i++) {
    const prevIndex = i === 0 ? j : i - 1;
    area += (xCoords[prevIndex] + xCoords[i]) * (yCoords[prevIndex] - yCoords[i]);
  }
  const absAreaSqMeters = Math.abs(area / 2);
  return Number((absAreaSqMeters / 4046.86).toFixed(2)); // return acres
};

export const Map: React.FC<MapProps> = ({
  properties = [],
  mode = 'view',
  center = [80.4365, 16.3067],
  zoom = 18.5,
  pickerLat = 16.3067,
  pickerLng = 80.4365,
  initialBoundary = [],
  onLocationSelected
}) => {
  const mapContainer = useRef<HTMLDivElement>(null);
  const mapRef = useRef<mapboxgl.Map | null>(null);
  const [loading, setLoading] = useState(true);
  const [isSatellite, setIsSatellite] = useState(false);
  const [drawMode, setDrawMode] = useState<'pin' | 'draw'>('pin');
  const [pointCount, setPointCount] = useState(0);

  // Reference lists for markers and points
  const pickerMarkerRef = useRef<mapboxgl.Marker | null>(null);
  const boundaryMarkersRef = useRef<mapboxgl.Marker[]>([]);
  const propertyMarkersRef = useRef<mapboxgl.Marker[]>([]);
  const boundaryPointsRef = useRef<[number, number][]>([]);

  // Refs for callbacks/changing props to prevent map re-init
  const onLocationSelectedRef = useRef(onLocationSelected);
  onLocationSelectedRef.current = onLocationSelected;
  const drawModeRef = useRef(drawMode);
  drawModeRef.current = drawMode;

  // Draw polygon line and fill layers
  const drawPolygon = useCallback(() => {
    const map = mapRef.current;
    const points = boundaryPointsRef.current;
    if (!map || points.length < 2) return;

    const lineSourceId = 'boundary-line-source';
    const fillSourceId = 'boundary-fill-source';
    const closedCoords = [...points, points[0]];

    const lineGeoJson = {
      type: 'FeatureCollection' as const,
      features: [{
        type: 'Feature' as const,
        geometry: { type: 'LineString' as const, coordinates: closedCoords },
        properties: {}
      }]
    };

    const fillGeoJson = {
      type: 'FeatureCollection' as const,
      features: [{
        type: 'Feature' as const,
        geometry: { type: 'Polygon' as const, coordinates: [closedCoords] },
        properties: {}
      }]
    };

    try {
      const lineSource = map.getSource(lineSourceId) as mapboxgl.GeoJSONSource;
      if (lineSource) {
        lineSource.setData(lineGeoJson);
      } else {
        map.addSource(lineSourceId, { type: 'geojson', data: lineGeoJson });
        map.addLayer({
          id: 'boundary-line',
          type: 'line',
          source: lineSourceId,
          paint: { 'line-color': '#10b981', 'line-width': 4 }
        });
      }

      if (points.length >= 3) {
        const fillSource = map.getSource(fillSourceId) as mapboxgl.GeoJSONSource;
        if (fillSource) {
          fillSource.setData(fillGeoJson);
        } else {
          map.addSource(fillSourceId, { type: 'geojson', data: fillGeoJson });
          map.addLayer({
            id: 'boundary-fill',
            type: 'fill',
            source: fillSourceId,
            paint: { 'fill-color': '#10b981', 'fill-opacity': 0.22 }
          }, 'boundary-line');
        }
      } else {
        if (map.getLayer('boundary-fill')) map.removeLayer('boundary-fill');
        if (map.getSource(fillSourceId)) map.removeSource(fillSourceId);
      }
    } catch (e) {
      console.error(e);
    }
  }, []);

  const handleReverseGeocode = useCallback(async (lng: number, lat: number, currentBoundary: [number, number][]) => {
    try {
      const details = await mapboxService.reverseGeocode(lng, lat);
      const calculatedArea = currentBoundary.length >= 3 ? calculatePolygonArea(currentBoundary) : undefined;
      if (onLocationSelectedRef.current) {
        onLocationSelectedRef.current({
          lat: Number(lat.toFixed(6)),
          lng: Number(lng.toFixed(6)),
          address: details.address || '',
          village: details.village || '',
          district: details.district || '',
          state: details.state || '',
          pincode: details.pincode || '',
          area: calculatedArea,
          boundary: currentBoundary.length > 0 ? [...currentBoundary] : undefined
        });
      }
    } catch {
      if (onLocationSelectedRef.current) {
        onLocationSelectedRef.current({
          lat: Number(lat.toFixed(6)),
          lng: Number(lng.toFixed(6)),
          address: '', village: '', district: '', state: '', pincode: '',
          boundary: currentBoundary.length > 0 ? [...currentBoundary] : undefined
        });
      }
    }
  }, []);

  const addBoundaryMarker = useCallback((lng: number, lat: number, index: number) => {
    const map = mapRef.current;
    if (!map) return;

    const el = document.createElement('div');
    el.className = 'w-3.5 h-3.5 bg-accent-500 border-2 border-white rounded-full shadow-lg cursor-pointer';
    el.addEventListener('click', (e) => e.stopPropagation());

    const marker = new mapboxgl.Marker({ element: el, draggable: true })
      .setLngLat([lng, lat])
      .addTo(map);

    marker.on('drag', () => {
      const pos = marker.getLngLat();
      boundaryPointsRef.current[index] = [pos.lng, pos.lat];
      drawPolygon();
    });

    marker.on('dragend', () => {
      const centroid = calculateCentroid(boundaryPointsRef.current);
      handleReverseGeocode(centroid[0], centroid[1], boundaryPointsRef.current);
    });

    boundaryMarkersRef.current.push(marker);
    setPointCount(boundaryPointsRef.current.length);
  }, [drawPolygon, handleReverseGeocode]);

  const clearBoundary = useCallback((emitEvent = false) => {
    boundaryPointsRef.current = [];
    setPointCount(0);
    boundaryMarkersRef.current.forEach(m => m.remove());
    boundaryMarkersRef.current = [];

    const map = mapRef.current;
    if (map) {
      if (map.getLayer('boundary-fill')) map.removeLayer('boundary-fill');
      if (map.getSource('boundary-fill-source')) map.removeSource('boundary-fill-source');
      if (map.getLayer('boundary-line')) map.removeLayer('boundary-line');
      if (map.getSource('boundary-line-source')) map.removeSource('boundary-line-source');
    }

    if (emitEvent) {
      const lat = pickerMarkerRef.current ? pickerMarkerRef.current.getLngLat().lat : pickerLat;
      const lng = pickerMarkerRef.current ? pickerMarkerRef.current.getLngLat().lng : pickerLng;
      handleReverseGeocode(lng, lat, []);
    }
  }, [pickerLat, pickerLng, handleReverseGeocode]);

  // Load boundary points on mount/update
  const loadBoundary = useCallback((boundary: [number, number][]) => {
    clearBoundary();
    if (!boundary || boundary.length === 0) return;

    boundaryPointsRef.current = [...boundary];
    setPointCount(boundary.length);
    boundary.forEach((pt, idx) => addBoundaryMarker(pt[0], pt[1], idx));

    const map = mapRef.current;
    if (map) {
      const cent = calculateCentroid(boundary);
      map.setCenter(cent);
      if (pickerMarkerRef.current) pickerMarkerRef.current.setLngLat(cent);
      drawPolygon();
    }
  }, [clearBoundary, addBoundaryMarker, drawPolygon]);

  // Initial mount - run exactly ONCE
  useEffect(() => {
    if (!mapContainer.current) return;

    const map = mapboxService.initializeMap(mapContainer.current, center, zoom);
    mapRef.current = map;

    map.on('style.load', () => {
      setLoading(false);
      map.resize();

      // Setup picker marker
      if (mode === 'picker') {
        pickerMarkerRef.current = new mapboxgl.Marker({ color: '#10b981', draggable: true })
          .setLngLat([pickerLng, pickerLat])
          .addTo(map);

        pickerMarkerRef.current.on('dragend', () => {
          const pos = pickerMarkerRef.current!.getLngLat();
          handleReverseGeocode(pos.lng, pos.lat, boundaryPointsRef.current);
        });

        // Initialize boundary if present
        if (initialBoundary && initialBoundary.length > 0) {
          loadBoundary(initialBoundary);
        } else {
          handleReverseGeocode(pickerLng, pickerLat, []);
        }
      } else if (mode === 'detail' && properties.length > 0) {
        const p = properties[0];
        mapboxService.addPropertyMarker(map, p);

        // Check if there is boundary drawn in the description
        const parsed = parseBoundaryFromDescription(p.description || '');

        if (parsed && parsed.length > 0) {
          boundaryPointsRef.current = parsed;
          parsed.forEach((pt) => {
            const el = document.createElement('div');
            el.className = 'w-2 h-2 bg-accent-500 rounded-full border border-white';
            new mapboxgl.Marker({ element: el }).setLngLat(pt).addTo(map);
          });
          drawPolygon();

          // Auto fit map bounds to show ALL boundary points with generous padding
          const bounds = new mapboxgl.LngLatBounds();
          parsed.forEach(pt => bounds.extend(pt));
          map.fitBounds(bounds, { padding: 140, maxZoom: 15, duration: 1000 });
        } else {
          // Draw fallback hexagon circle
          const areaSqMeters = (p.area || 1) * 4046.86;
          const r = Math.sqrt(areaSqMeters / Math.PI);
          const pts: [number, number][] = [];
          const R = 6378137;
          for (let i = 0; i < 6; i++) {
            const angle = (i * 60) * Math.PI / 180;
            const dLat = (r * Math.sin(angle)) / R * 180 / Math.PI;
            const dLng = (r * Math.cos(angle)) / (R * Math.cos(p.latitude * Math.PI / 180)) * 180 / Math.PI;
            pts.push([p.longitude + dLng, p.latitude + dLat]);
          }
          pts.push(pts[0]);
          map.addSource('fallback-boundary', {
            type: 'geojson',
            data: { type: 'Feature', geometry: { type: 'Polygon', coordinates: [pts] }, properties: {} }
          });
          map.addLayer({
            id: 'fallback-fill', type: 'fill', source: 'fallback-boundary', paint: { 'fill-color': '#10b981', 'fill-opacity': 0.15 }
          });
          map.addLayer({
            id: 'fallback-line', type: 'line', source: 'fallback-boundary', paint: { 'line-color': '#10b981', 'line-width': 2, 'line-dasharray': [2, 2] }
          });
          // Fit bounds to fallback hexagon too
          const fbBounds = new mapboxgl.LngLatBounds();
          pts.forEach(pt => fbBounds.extend(pt));
          map.fitBounds(fbBounds, { padding: 140, maxZoom: 15, duration: 1000 });
        }
      } else if (mode === 'view') {
        propertyMarkersRef.current.forEach(m => m.remove());
        propertyMarkersRef.current = properties.map(p => mapboxService.addPropertyMarker(map, p));

        const features = properties.map(p => {
          const parsed = parseBoundaryFromDescription(p.description || '');
          if (parsed && parsed.length > 2) {
            const closedCoords = [...parsed, parsed[0]];
            return {
              type: 'Feature',
              geometry: { type: 'Polygon', coordinates: [closedCoords] },
              properties: { id: p.id, category: p.category }
            };
          }
          return null;
        }).filter(Boolean) as any[];

        if (features.length > 0) {
          if (map.getSource('view-polygons')) {
            (map.getSource('view-polygons') as mapboxgl.GeoJSONSource).setData({ type: 'FeatureCollection', features });
          } else {
            map.addSource('view-polygons', { type: 'geojson', data: { type: 'FeatureCollection', features } });
            map.addLayer({
              id: 'view-polygons-fill', type: 'fill', source: 'view-polygons',
              paint: { 'fill-color': '#3b82f6', 'fill-opacity': 0.15 }
            });
            map.addLayer({
              id: 'view-polygons-line', type: 'line', source: 'view-polygons',
              paint: { 'line-color': '#3b82f6', 'line-width': 2 }
            });
          }
          // Fit bounds to show all properties if any exist
          const bounds = new mapboxgl.LngLatBounds();
          features.forEach(f => {
            f.geometry.coordinates[0].forEach((coord: [number, number]) => bounds.extend(coord));
          });
          map.fitBounds(bounds, { padding: 40, duration: 1000 });
        }
      }
    });

    map.on('click', (e: any) => {
      if (mode !== 'picker') return;

      if (drawModeRef.current === 'pin') {
        if (pickerMarkerRef.current) {
          pickerMarkerRef.current.setLngLat(e.lngLat);
          handleReverseGeocode(e.lngLat.lng, e.lngLat.lat, boundaryPointsRef.current);
        }
      } else {
        const pt: [number, number] = [e.lngLat.lng, e.lngLat.lat];
        boundaryPointsRef.current = [...boundaryPointsRef.current, pt];
        addBoundaryMarker(pt[0], pt[1], boundaryPointsRef.current.length - 1);
        drawPolygon();

        const cent = calculateCentroid(boundaryPointsRef.current);
        handleReverseGeocode(cent[0], cent[1], boundaryPointsRef.current);
      }
    });

    return () => {
      if (pickerMarkerRef.current) pickerMarkerRef.current.remove();
      boundaryMarkersRef.current.forEach(m => m.remove());
      propertyMarkersRef.current.forEach(m => m.remove());
      map.remove();
    };
  }, []); // Run exactly once!

  // Watch properties updates (only in view mode, no re-initialization)
  useEffect(() => {
    const map = mapRef.current;
    if (map && map.isStyleLoaded() && mode === 'view') {
      propertyMarkersRef.current.forEach(m => m.remove());
      propertyMarkersRef.current = properties.map(p => mapboxService.addPropertyMarker(map, p));

      const features = properties.map(p => {
        const parsed = parseBoundaryFromDescription(p.description || '');
        if (parsed && parsed.length > 2) {
          const closedCoords = [...parsed, parsed[0]];
          return {
            type: 'Feature',
            geometry: { type: 'Polygon', coordinates: [closedCoords] },
            properties: { id: p.id, category: p.category }
          };
        }
        return null;
      }).filter(Boolean) as any[];

      if (features.length > 0) {
        if (map.getSource('view-polygons')) {
          (map.getSource('view-polygons') as mapboxgl.GeoJSONSource).setData({ type: 'FeatureCollection', features });
        } else {
          map.addSource('view-polygons', { type: 'geojson', data: { type: 'FeatureCollection', features } });
          map.addLayer({
            id: 'view-polygons-fill', type: 'fill', source: 'view-polygons',
            paint: { 'fill-color': '#3b82f6', 'fill-opacity': 0.15 }
          });
          map.addLayer({
            id: 'view-polygons-line', type: 'line', source: 'view-polygons',
            paint: { 'line-color': '#3b82f6', 'line-width': 2 }
          });
        }
      } else {
        if (map.getSource('view-polygons')) {
          (map.getSource('view-polygons') as mapboxgl.GeoJSONSource).setData({ type: 'FeatureCollection', features: [] });
        }
      }
    }
  }, [properties, mode]);

  // Handle switching drawMode
  useEffect(() => {
    const map = mapRef.current;
    if (!map) return;
    if (drawMode === 'pin') {
      if (pickerMarkerRef.current) pickerMarkerRef.current.addTo(map);
      boundaryMarkersRef.current.forEach(m => m.remove());
    } else {
      if (pickerMarkerRef.current) pickerMarkerRef.current.remove();
      boundaryMarkersRef.current.forEach(m => m.addTo(map));
    }
  }, [drawMode]);

  const toggleStyle = () => {
    const map = mapRef.current;
    if (!map) return;
    const nextStyle = isSatellite ? 'mapbox://styles/mapbox/streets-v12' : 'mapbox://styles/mapbox/satellite-streets-v12';
    map.setStyle(nextStyle);
    setIsSatellite(!isSatellite);
  };

  return (
    <div className="relative w-full h-full min-h-[350px] rounded-2xl overflow-hidden border border-white/10 shadow-lg">
      <div ref={mapContainer} className="w-full h-full absolute inset-0"></div>

      {loading && (
        <div className="absolute inset-0 bg-dark-950/60 backdrop-blur-xs flex items-center justify-center z-50">
          <div className="glass-card px-5 py-3 flex items-center gap-3">
            <Loader2 className="w-5 h-5 text-primary-400 animate-spin" />
            <span className="text-white text-sm font-medium">Loading map layers...</span>
          </div>
        </div>
      )}

      {mode === 'picker' && !loading && (
        <div className="absolute top-4 left-4 z-40 glass-card !bg-dark-950/85 backdrop-blur-md border-white/10 p-3 flex flex-col gap-2 max-w-[200px] shadow-2xl">
          <span className="text-[10px] font-bold text-white uppercase tracking-wider">Boundary Drawing Tool</span>
          <div className="flex bg-white/[0.04] p-0.5 rounded-lg border border-white/[0.06]">
            <button
              type="button"
              onClick={() => setDrawMode('pin')}
              className={`flex-1 py-1 text-[9px] font-bold rounded-md transition-all text-center flex items-center justify-center gap-1
                ${drawMode === 'pin' ? 'bg-white/10 text-white shadow-xs' : 'text-dark-500 hover:text-dark-300'}`}
            >
              <MapPin className="w-2.5 h-2.5" /> Pin Point
            </button>
            <button
              type="button"
              onClick={() => setDrawMode('draw')}
              className={`flex-1 py-1 text-[9px] font-bold rounded-md transition-all text-center flex items-center justify-center gap-1
                ${drawMode === 'draw' ? 'bg-white/10 text-white shadow-xs' : 'text-dark-500 hover:text-dark-300'}`}
            >
              Draw Area
            </button>
          </div>

          {drawMode === 'draw' && (
            <div className="space-y-2 pt-1 border-t border-white/[0.06] text-left">
              <p className="text-[9px] text-dark-400 leading-tight">
                Click map to add boundary points. Drag points to adjust.
              </p>
              {pointCount > 0 && (
                <div className="flex justify-between items-center text-[9px] text-accent-400 font-semibold">
                  <span>Points Placed:</span>
                  <span>{pointCount}</span>
                </div>
              )}
              <button
                type="button"
                onClick={() => clearBoundary(true)}
                className="w-full py-1.5 bg-danger-500/10 hover:bg-danger-500/20 text-danger-400 font-bold text-[9px] rounded-lg transition border border-danger-500/20 flex items-center justify-center gap-1"
              >
                <Trash2 className="w-2.5 h-2.5" /> Clear Points
              </button>
            </div>
          )}
        </div>
      )}

      <button 
        onClick={toggleStyle}
        className="absolute bottom-4 left-4 glass-card !bg-dark-950/85 hover:!bg-white/[0.08] text-white font-semibold text-xs px-3 py-2 rounded-xl shadow-md border border-white/10 transition z-40 flex items-center gap-1.5 backdrop-blur-xs"
      >
        <span className={`w-2 h-2 rounded-full ${isSatellite ? 'bg-cyan-400' : 'bg-accent-400 animate-pulse'}`}></span>
        {isSatellite ? 'Street View' : 'Satellite View'}
      </button>
    </div>
  );
};

// src/app/shared/components/map/map.component.ts
import { Component, ElementRef, EventEmitter, Input, Output, ViewChild, AfterViewInit, OnChanges, SimpleChanges, OnDestroy, inject, NgZone, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MapboxService } from '../../../core/services/mapbox.service';
import { Property } from '../../../core/models/property.models';
import mapboxgl from 'mapbox-gl';

@Component({
  selector: 'app-map',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="relative w-full h-full min-h-[350px] rounded-2xl overflow-hidden shadow-inner border border-slate-200">
      <div #mapContainer class="w-full h-full absolute inset-0"></div>
      
      <!-- SVG Overlay for drawing closed boundary lines between dots -->
      <svg 
        *ngIf="!!map && (mode === 'detail' || (mode === 'picker' && drawMode === 'draw')) && boundaryPoints.length >= 2"
        width="100%"
        height="100%"
        style="display: block; position: absolute; top: 0; left: 0; pointer-events: none; z-index: 30;">
        <polygon 
          [attr.points]="svgPoints" 
          fill="rgba(16, 185, 129, 0.22)" 
          stroke="#10b981" 
          stroke-width="4" 
          stroke-linejoin="round"
        />
      </svg>

      <!-- Loading Overlay -->
      <div *ngIf="loading" class="absolute inset-0 bg-slate-900/40 backdrop-blur-xs flex items-center justify-center z-50">
        <div class="bg-white/95 px-6 py-4 rounded-xl shadow-lg border border-slate-100 flex items-center gap-3">
          <div class="w-5 h-5 border-2 border-emerald-500 border-t-transparent rounded-full animate-spin"></div>
          <span class="text-slate-700 font-medium text-sm">Loading map layers...</span>
        </div>
      </div>

      <!-- Drawing Controls (Picker Mode Only) -->
      <div *ngIf="mode === 'picker' && !!map" class="absolute top-4 left-4 z-40 bg-white/95 px-3.5 py-2.5 rounded-xl shadow-lg border border-slate-200/50 flex flex-col gap-2 backdrop-blur-xs max-w-[180px]">
        <span class="text-[11px] font-bold text-slate-800 tracking-tight">Land Boundary Tool</span>
        <div class="flex gap-1 bg-slate-100 p-0.5 rounded-lg border border-slate-200/30">
          <button 
            type="button"
            (click)="setDrawMode('pin')"
            [class.bg-white]="drawMode === 'pin'"
            [class.shadow-xs]="drawMode === 'pin'"
            [class.text-slate-800]="drawMode === 'pin'"
            [class.text-slate-500]="drawMode !== 'pin'"
            class="flex-1 py-1 text-[9px] font-bold rounded-md transition-all text-center">
            Pin Point
          </button>
          <button 
            type="button"
            (click)="setDrawMode('draw')"
            [class.bg-white]="drawMode === 'draw'"
            [class.shadow-xs]="drawMode === 'draw'"
            [class.text-slate-800]="drawMode === 'draw'"
            [class.text-slate-500]="drawMode !== 'draw'"
            class="flex-1 py-1 text-[9px] font-bold rounded-md transition-all text-center">
            Draw Area
          </button>
        </div>
        <div *ngIf="drawMode === 'draw'" class="space-y-1.5 pt-1.5 border-t border-slate-100">
          <p class="text-[9px] text-slate-500 leading-tight">Click map to add boundary dots. Drag dots to adjust.</p>
          <button 
            type="button"
            (click)="clearBoundary()"
            class="w-full py-1.5 bg-rose-50 hover:bg-rose-100 text-rose-600 font-bold text-[9px] rounded-lg transition border border-rose-200/20">
            Clear Dots
          </button>
        </div>
      </div>

      <!-- Sat/Street View Toggle -->
      <button 
        *ngIf="map"
        (click)="toggleMapStyle()"
        class="absolute bottom-4 left-4 bg-white/90 hover:bg-white text-slate-800 font-semibold text-xs px-3 py-2 rounded-lg shadow-md border border-slate-200 transition z-40 flex items-center gap-1.5 backdrop-blur-xs">
        <span class="w-2.5 h-2.5 rounded-full" [ngClass]="isSatellite ? 'bg-blue-500' : 'bg-emerald-600'"></span>
        {{ isSatellite ? 'Switch to Street View' : 'Switch to Satellite View' }}
      </button>
    </div>
  `
})
export class MapComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input() properties: Property[] = [];
  @Input() mode: 'view' | 'picker' | 'detail' = 'view';
  @Input() center: [number, number] = [80.4365, 16.3067]; // default Guntur/AP
  @Input() zoom = 10;
  @Input() pickerLat = 16.3067;
  @Input() pickerLng = 80.4365;
  @Input() initialBoundary: [number, number][] = [];

  @Output() locationSelected = new EventEmitter<{
    lat: number;
    lng: number;
    address: string;
    village: string;
    district: string;
    state: string;
    pincode: string;
    area?: number;
    boundary?: [number, number][];
  }>();

  @ViewChild('mapContainer') mapContainer!: ElementRef;

  map: mapboxgl.Map | any = null;
  isSatellite = false;
  loading = true;
  styleLoaded = false;
  drawMode: 'pin' | 'draw' = 'pin';
  boundaryPoints: [number, number][] = [];
  private boundaryMarkers: mapboxgl.Marker[] = [];
  private markers: mapboxgl.Marker[] = [];
  private pickerMarker: mapboxgl.Marker | null = null;
  private mapboxService = inject(MapboxService);
  private zone = inject(NgZone);
  private cdr = inject(ChangeDetectorRef);

  ngAfterViewInit(): void {
    this.initMap();
    // Safety resize to handle dynamic tab layout rendering transitions
    setTimeout(() => {
      if (this.map) {
        this.map.resize();
      }
    }, 500);
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['properties'] && !changes['properties'].firstChange && this.map) {
      this.updateMarkers();
    }
    if (changes['initialBoundary'] && this.map) {
      this.loadInitialBoundaryPoints(changes['initialBoundary'].currentValue);
    }
  }

  private loadInitialBoundaryPoints(boundary: [number, number][]): void {
    this.clearBoundary();
    if (!boundary || boundary.length === 0) return;

    this.boundaryPoints = [...boundary];
    this.boundaryPoints.forEach((pt, index) => {
      this.addBoundaryPointMarker(pt[0], pt[1], index);
    });

    if (this.boundaryPoints.length > 0) {
      const center = this.calculateCentroid(this.boundaryPoints);
      this.map.setCenter(center);
      this.map.setZoom(15);
      
      if (this.pickerMarker) {
        this.pickerMarker.setLngLat(center);
      }
    }

    this.drawPolygon();
  }

  private initMap(): void {
    try {
      this.map = this.mapboxService.initializeMap(
        this.mapContainer.nativeElement,
        this.center,
        this.zoom
      );

      const onMapLoad = () => {
        this.zone.run(() => {
          this.loading = false;
          this.styleLoaded = true;
          
          if (this.map) {
            this.map.resize();
          }

          // Redraw custom boundaries and markers when map style loaded/reloaded
          if (this.boundaryPoints.length >= 2) {
            this.drawPolygon();
          }

          if (this.mode === 'picker') {
            this.setupPickerMode();
          } else if (this.mode === 'detail') {
            this.setupDetailMode();
          } else {
            this.updateMarkers();
          }
          
          this.cdr.detectChanges();
        });
      };

      // Safety timeout fallback to guarantee spinner is hidden
      setTimeout(() => {
        this.zone.run(() => {
          this.loading = false;
          this.cdr.detectChanges();
        });
      }, 1500);

      // Listen on style loaded events persistently to rebuild vector layers on style toggle
      this.map.on('style.load', onMapLoad);
      
      // Bind click handler once on the map instance to handle both pin dragging and boundary plotting
      this.map.on('click', (e: any) => {
        this.zone.run(() => {
          if (this.mode !== 'picker') return;

          if (this.drawMode === 'pin') {
            if (this.pickerMarker) {
              this.pickerMarker.setLngLat(e.lngLat);
              this.handleReverseGeocode(e.lngLat.lng, e.lngLat.lat);
            }
          } else {
            // Draw mode - place vertex dot
            const point: [number, number] = [e.lngLat.lng, e.lngLat.lat];
            this.boundaryPoints = [...this.boundaryPoints, point];
            this.addBoundaryPointMarker(point[0], point[1], this.boundaryPoints.length - 1);
            this.drawPolygon();
            this.updateBoundaryResults();
          }
        });
      });

      // Listen to map movements (pan/zoom/drag) to redraw the SVG overlay lines dynamically
      this.map.on('move', () => {
        this.zone.run(() => {}); // Trigger Angular change detection reflow
      });

      // Trigger initial load if ready
      if (this.map.isStyleLoaded()) {
        onMapLoad();
      }
    } catch (e) {
      console.error('Error loading Mapbox', e);
      this.zone.run(() => {
        this.loading = false;
      });
    }
  }

  setDrawMode(mode: 'pin' | 'draw'): void {
    this.drawMode = mode;
    this.clearBoundary();
    
    if (mode === 'pin') {
      if (this.pickerMarker) {
        this.pickerMarker.addTo(this.map);
      } else {
        this.setupPickerMode();
      }
    } else {
      if (this.pickerMarker) {
        this.pickerMarker.remove();
      }
    }
  }

  private setupPickerMode(): void {
    if (this.pickerMarker) {
      this.pickerMarker.remove();
    }

    if (this.map) {
      this.map.resize();
    }

    // Put a draggable marker at picker coords
    const color = '#10b981'; // emerald picker marker
    this.pickerMarker = new mapboxgl.Marker({ color, draggable: true })
      .setLngLat([this.pickerLng, this.pickerLat])
      .addTo(this.map);

    this.map.setCenter([this.pickerLng, this.pickerLat]);
    this.map.setZoom(14);

    const onMarkerMove = () => {
      const lngLat = this.pickerMarker!.getLngLat();
      this.zone.run(() => {
        this.handleReverseGeocode(lngLat.lng, lngLat.lat);
      });
    };

    this.pickerMarker.on('dragend', onMarkerMove);

    // Initial emit
    this.zone.run(() => {
      this.handleReverseGeocode(this.pickerLng, this.pickerLat);
    });
  }

  private addBoundaryPointMarker(lng: number, lat: number, index: number): void {
    const el = document.createElement('div');
    el.style.width = '14px';
    el.style.height = '14px';
    el.style.backgroundColor = '#10b981';
    el.style.border = '2px solid #ffffff';
    el.style.borderRadius = '50%';
    el.style.boxShadow = '0 2px 6px rgba(0,0,0,0.3)';
    el.style.cursor = 'pointer';
    el.style.display = 'block';

    // Prevent map click bubble when clicking on the boundary dot element
    el.addEventListener('click', (event) => {
      event.stopPropagation();
    });

    const marker = new mapboxgl.Marker({ element: el, draggable: true })
      .setLngLat([lng, lat])
      .addTo(this.map);

    marker.on('drag', () => {
      this.zone.run(() => {
        const newLngLat = marker.getLngLat();
        const updated = [...this.boundaryPoints];
        updated[index] = [newLngLat.lng, newLngLat.lat];
        this.boundaryPoints = updated;
        this.drawPolygon();
        this.updateBoundaryResults();
      });
    });

    this.boundaryMarkers.push(marker);
  }

  get svgPoints(): string {
    if (!this.map || this.boundaryPoints.length < 2) return '';
    return this.boundaryPoints
      .map(pt => {
        try {
          const pix = this.map.project(pt);
          return `${pix.x},${pix.y}`;
        } catch (e) {
          return '';
        }
      })
      .filter(Boolean)
      .join(' ');
  }

  private drawPolygon(): void {
    if (!this.map || this.boundaryPoints.length < 2) return;

    const lineSourceId = 'boundary-line-source';
    const fillSourceId = 'boundary-fill-source';

    const closedCoords = [...this.boundaryPoints];
    closedCoords.push(closedCoords[0]); // Connect back to first dot

    const lineGeoJson = {
      type: 'FeatureCollection' as const,
      features: [{
        type: 'Feature' as const,
        geometry: {
          type: 'LineString' as const,
          coordinates: closedCoords
        },
        properties: {}
      }]
    };

    const fillGeoJson = {
      type: 'FeatureCollection' as const,
      features: [{
        type: 'Feature' as const,
        geometry: {
          type: 'Polygon' as const,
          coordinates: [closedCoords]
        },
        properties: {}
      }]
    };

    try {
      // 1. Draw/Update Line Outline
      const lineSource = this.map.getSource(lineSourceId) as mapboxgl.GeoJSONSource;
      if (lineSource) {
        lineSource.setData(lineGeoJson);
      } else {
        this.map.addSource(lineSourceId, {
          type: 'geojson',
          data: lineGeoJson
        });

        this.map.addLayer({
          id: 'boundary-line',
          type: 'line',
          source: lineSourceId,
          paint: {
            'line-color': '#10b981',
            'line-width': 4
          }
        });
      }

      // 2. Draw/Update Shaded Fill (Only if 3 or more dots)
      if (this.boundaryPoints.length >= 3) {
        const fillSource = this.map.getSource(fillSourceId) as mapboxgl.GeoJSONSource;
        if (fillSource) {
          fillSource.setData(fillGeoJson);
        } else {
          this.map.addSource(fillSourceId, {
            type: 'geojson',
            data: fillGeoJson
          });

          // Insert fill layer beneath outline for visual structure
          this.map.addLayer({
            id: 'boundary-fill',
            type: 'fill',
            source: fillSourceId,
            paint: {
              'fill-color': '#10b981',
              'fill-opacity': 0.22
            }
          }, 'boundary-line');
        }
      } else {
        // If we drop below 3 points, clean up fill layer/source
        if (this.map.getLayer('boundary-fill')) this.map.removeLayer('boundary-fill');
        if (this.map.getSource(fillSourceId)) this.map.removeSource(fillSourceId);
      }
    } catch (e) {
      console.error('Error drawing boundary polygon', e);
    }
  }

  private updateBoundaryResults(): void {
    if (this.boundaryPoints.length === 0) return;

    let center: [number, number];
    let area = 0;

    if (this.boundaryPoints.length === 1) {
      center = this.boundaryPoints[0];
    } else if (this.boundaryPoints.length === 2) {
      center = [
        (this.boundaryPoints[0][0] + this.boundaryPoints[1][0]) / 2,
        (this.boundaryPoints[0][1] + this.boundaryPoints[1][1]) / 2
      ];
    } else {
      center = this.calculateCentroid(this.boundaryPoints);
      area = this.calculatePolygonArea(this.boundaryPoints);
    }

    this.mapboxService.reverseGeocode(center[0], center[1]).subscribe({
      next: (details) => {
        this.locationSelected.emit({
          lat: Number(center[1].toFixed(6)),
          lng: Number(center[0].toFixed(6)),
          address: details.address || '',
          village: details.village || '',
          district: details.district || '',
          state: details.state || '',
          pincode: details.pincode || '',
          area: area > 0 ? area : undefined,
          boundary: [...this.boundaryPoints]
        });
      }
    });
  }

  private calculateCentroid(points: [number, number][]): [number, number] {
    let sumLng = 0;
    let sumLat = 0;
    points.forEach(pt => {
      sumLng += pt[0];
      sumLat += pt[1];
    });
    return [sumLng / points.length, sumLat / points.length];
  }

  private calculatePolygonArea(points: [number, number][]): number {
    if (points.length < 3) return 0;
    
    // Convert to local mercator flat approximations
    const R = 6378137;
    const xCoords = points.map(pt => pt[0] * Math.PI / 180 * R * Math.cos(pt[1] * Math.PI / 180));
    const yCoords = points.map(pt => pt[1] * Math.PI / 180 * R);

    let area = 0;
    const j = xCoords.length - 1;
    for (let i = 0; i < xCoords.length; i++) {
      const prevIndex = i === 0 ? j : i - 1;
      area += (xCoords[prevIndex] + xCoords[i]) * (yCoords[prevIndex] - yCoords[i]);
    }
    
    const absAreaSqMeters = Math.abs(area / 2);
    const acres = absAreaSqMeters / 4046.86;
    return Number(acres.toFixed(2));
  }

  clearBoundary(): void {
    this.boundaryPoints = [];
    this.boundaryMarkers.forEach(m => m.remove());
    this.boundaryMarkers = [];
    
    const lineSourceId = 'boundary-line-source';
    const fillSourceId = 'boundary-fill-source';

    if (this.map) {
      if (this.map.getLayer('boundary-fill')) {
        this.map.removeLayer('boundary-fill');
      }
      if (this.map.getSource(fillSourceId)) {
        this.map.removeSource(fillSourceId);
      }

      if (this.map.getLayer('boundary-line')) {
        this.map.removeLayer('boundary-line');
      }
      if (this.map.getSource(lineSourceId)) {
        this.map.removeSource(lineSourceId);
      }
    }
  }

  private handleReverseGeocode(lng: number, lat: number): void {
    this.mapboxService.reverseGeocode(lng, lat).subscribe({
      next: (details) => {
        this.locationSelected.emit({
          lat,
          lng,
          address: details.address || '',
          village: details.village || '',
          district: details.district || '',
          state: details.state || '',
          pincode: details.pincode || ''
        });
      },
      error: () => {
        this.locationSelected.emit({
          lat,
          lng,
          address: '',
          village: '',
          district: '',
          state: '',
          pincode: ''
        });
      }
    });
  }

  private parseBoundaryFromDescription(desc: string): [number, number][] | null {
    try {
      const match = desc.match(/\[BOUNDS\]:\s*(\[.*?\])/);
      if (match && match[1]) {
        return JSON.parse(match[1]);
      }
    } catch (e) {
      console.error('Failed to parse boundary coordinates', e);
    }
    return null;
  }

  private setupDetailMode(): void {
    if (this.properties.length > 0) {
      const p = this.properties[0];
      this.mapboxService.addPropertyMarker(this.map, p);
      
      const customBoundary = this.parseBoundaryFromDescription(p.description || '');
      if (customBoundary && customBoundary.length > 0) {
        this.boundaryPoints = customBoundary;
        this.drawMode = 'draw';
        
        // Also place static markers (dots) on each vertex of the boundary in detail view for visual clarity
        this.boundaryPoints.forEach(pt => {
          const el = document.createElement('div');
          el.style.width = '8px';
          el.style.height = '8px';
          el.style.backgroundColor = '#10b981';
          el.style.border = '1px solid #ffffff';
          el.style.borderRadius = '50%';
          el.style.boxShadow = '0 1px 3px rgba(0,0,0,0.2)';
          
          const m = new mapboxgl.Marker({ element: el })
            .setLngLat(pt)
            .addTo(this.map);
          this.markers.push(m);
        });
      } else {
        // Draw details boundary hexagon approximation fallback
        this.drawVisualBoundary(p.longitude, p.latitude, p.area);
      }

      this.map.setCenter([p.longitude, p.latitude]);
      this.map.setZoom(16);
    } else {
      new mapboxgl.Marker({ color: '#10b981' })
        .setLngLat(this.center)
        .addTo(this.map);
    }
  }

  private drawVisualBoundary(lng: number, lat: number, areaInAcres: number): void {
    if (!this.map) return;

    // 1 Acre = 4046.86 sq meters. Circle Area = pi * r^2 => r = sqrt(Area / pi)
    const areaSqMeters = (areaInAcres || 1) * 4046.86;
    const radius = Math.sqrt(areaSqMeters / Math.PI);

    const points: [number, number][] = [];
    const R = 6378137;
    for (let i = 0; i < 6; i++) {
      const angle = (i * 60) * Math.PI / 180;
      const dLat = (radius * Math.sin(angle)) / R * 180 / Math.PI;
      const dLng = (radius * Math.cos(angle)) / (R * Math.cos(lat * Math.PI / 180)) * 180 / Math.PI;
      points.push([lng + dLng, lat + dLat]);
    }
    points.push(points[0]);

    const sourceId = 'property-detail-boundary';
    
    if (this.map.getSource(sourceId)) {
      this.map.removeLayer('property-detail-fill');
      this.map.removeLayer('property-detail-line');
      this.map.removeSource(sourceId);
    }

    this.map.addSource(sourceId, {
      type: 'geojson',
      data: {
        type: 'Feature',
        geometry: {
          type: 'Polygon',
          coordinates: [points]
        },
        properties: {}
      }
    });

    this.map.addLayer({
      id: 'property-detail-fill',
      type: 'fill',
      source: sourceId,
      paint: {
        'fill-color': '#10b981',
        'fill-opacity': 0.15
      }
    });

    this.map.addLayer({
      id: 'property-detail-line',
      type: 'line',
      source: sourceId,
      paint: {
        'line-color': '#10b981',
        'line-width': 2,
        'line-dasharray': [2, 2]
      }
    });
  }

  private updateMarkers(): void {
    this.clearMarkers();

    if (this.mode === 'view') {
      const sourceId = 'properties-source';
      
      if (this.map.getSource(sourceId)) {
        this.map.removeLayer('cluster-count');
        this.map.removeLayer('clusters');
        this.map.removeSource(sourceId);
      }

      const features = this.properties.map(p => ({
        type: 'Feature' as const,
        geometry: {
          type: 'Point' as const,
          coordinates: [p.longitude, p.latitude]
        },
        properties: {
          id: p.id,
          title: p.title,
          price: p.price,
          area: p.area,
          status: p.status
        }
      }));

      this.map.addSource(sourceId, {
        type: 'geojson',
        data: {
          type: 'FeatureCollection',
          features
        },
        cluster: true,
        clusterMaxZoom: 14,
        clusterRadius: 50
      });

      this.map.addLayer({
        id: 'clusters',
        type: 'circle',
        source: sourceId,
        filter: ['has', 'point_count'],
        paint: {
          'circle-color': '#0f766e',
          'circle-radius': ['step', ['get', 'point_count'], 20, 10, 30, 50, 40],
          'circle-stroke-width': 2,
          'circle-stroke-color': '#ffffff'
        }
      });

      this.map.addLayer({
        id: 'cluster-count',
        type: 'symbol',
        source: sourceId,
        filter: ['has', 'point_count'],
        layout: {
          'text-field': '{point_count_abbreviated}',
          'text-font': ['DIN Offc Pro Medium', 'Arial Unicode MS Bold'],
          'text-size': 12
        },
        paint: {
          'text-color': '#ffffff'
        }
      });

      this.map.on('click', 'clusters', (e: any) => {
        const features = this.map.queryRenderedFeatures(e.point, { layers: ['clusters'] });
        const clusterId = features[0].properties!['cluster_id'];
        (this.map.getSource(sourceId) as mapboxgl.GeoJSONSource).getClusterExpansionZoom(clusterId, (err, zoom) => {
          if (err) return;
          this.map.easeTo({
            center: (features[0].geometry as any).coordinates,
            zoom: zoom! + 1
          });
        });
      });

      const updateUnclusteredMarkers = () => {
        this.clearMarkers();
        this.properties.forEach(p => {
          const marker = this.mapboxService.addPropertyMarker(this.map, p, (clicked) => {
            this.map.easeTo({ center: [clicked.longitude, clicked.latitude], zoom: 12 });
          });
          this.markers.push(marker);
        });
      };

      updateUnclusteredMarkers();
    }
  }

  private clearMarkers(): void {
    this.markers.forEach(m => m.remove());
    this.markers = [];
  }

  toggleMapStyle(): void {
    if (!this.map) return;
    this.isSatellite = !this.isSatellite;
    const style = this.isSatellite
      ? 'mapbox://styles/mapbox/satellite-streets-v12'
      : 'mapbox://styles/mapbox/streets-v12';
    
    this.styleLoaded = false;
    this.map.setStyle(style);
    
    setTimeout(() => {
      if (this.map) {
        this.map.resize();
      }
    }, 200);
  }

  ngOnDestroy(): void {
    this.clearMarkers();
    this.clearBoundary();
    if (this.pickerMarker) this.pickerMarker.remove();
    if (this.map) this.map.remove();
  }
}
